export default {
    products: [
        {
            id: 1,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 2,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 3,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 4,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 5,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 6,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 7,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        },
        {
            id: 8,
            name: 'Slim Shirt',
            category: 'Shirt',
            image: 'https://picsum.photos/200',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
        }
    ]
}